using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace PruebaRegex
{
    class Program
    {
        static Parada[] Recorrido1 = new[] { 
            new Parada { Id = 1 }, 
            new Parada { Id = 2 },
            new Parada { Id = 3 },
            new Parada { Id = 4 },
        };

        static Parada[] Prueba1 = new[] {
            new Parada { Id = 1 },
            new Parada { Id = 2 },
            new Parada { Id = 3 },
            new Parada { Id = 1 },
            new Parada { Id = 2 },
            new Parada { Id = 3 },
            new Parada { Id = 1 },
            new Parada { Id = 2 },
            new Parada { Id = 4 },
            new Parada { Id = 3 },
        };

        static Parada[] Prueba2 = new[] {
            new Parada { Id = 1 },
            new Parada { Id = 2 },
            //new Parada { Id = 3 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            //new Parada { Id = 1 },
            new Parada { Id = 2 },
            new Parada { Id = 3 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },
            new Parada { Id = 10 }, new Parada { Id = 11 }, new Parada { Id = 12 },

            new Parada { Id = 1 },
            //new Parada { Id = 2 },
            new Parada { Id = 3 },
        };

        static string CreatePruebaFromParadas(IEnumerable<Parada> paradas, Func<Parada, string> nameBuilder)
        {
            StringBuilder sbRegexPattern = new StringBuilder();

            foreach (var parada in paradas)
            {
                sbRegexPattern.Append(nameBuilder(parada));
            }

            return sbRegexPattern.ToString();
        }

        static string CreateRegexPatternFromParadas(IEnumerable<Parada> paradas, Func<Parada, string> nameBuilder)
        {
            StringBuilder sbRegexPattern = new StringBuilder();

            foreach (var parada in paradas)
            {
                sbRegexPattern.Append('(');
                sbRegexPattern.Append(nameBuilder(parada));
                sbRegexPattern.Append(')');
                sbRegexPattern.Append('*');
            }

            return sbRegexPattern.ToString();
        }

        static Regex CreateRegexFromParadas(IEnumerable<Parada> paradas, Func<Parada, string> nameBuilder)
        {
            var pattern = CreateRegexPatternFromParadas(paradas, nameBuilder);
            return new Regex(pattern);
        }

        static void Main(string[] args)
        {
            string  pattern = CreateRegexPatternFromParadas(Recorrido1, (p) => $"p{p.Id:0000}");
            Regex   regex   = new (pattern);
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(pattern);

            string prueba1 = CreatePruebaFromParadas(Prueba1, (p) => $"p{p.Id:0000}");
            string prueba2 = CreatePruebaFromParadas(Prueba2, (p) => $"p{p.Id:0000}");
            string prueba3 = 
                prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 +
                prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 +
                prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 +
                prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 +
                prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 +
                prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 +
                prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2 + prueba2
            ;

            Console.ForegroundColor = ConsoleColor.Yellow;

            Console.WriteLine(prueba1);
            Console.WriteLine(prueba2);

            Console.ForegroundColor = ConsoleColor.Green;

            int start   = Environment.TickCount;
            var matches = regex.Matches(prueba3);
            int end     = Environment.TickCount;

            foreach (Match match in matches)
            {
                if (string.IsNullOrEmpty(match.Value))
                {
                    //Console.ForegroundColor = ConsoleColor.DarkGray;
                    //Console.WriteLine($"val={match.Value} index={match.Index}");
                }
                else
                {
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.WriteLine($"val={match.Value} index={match.Index}");
                }
            }

            Console.WriteLine($"{end - start} milis");
            Console.ForegroundColor = ConsoleColor.Gray;
        }
    }

    public class Parada
    {
        public int Id { get; set; }
    }
}
